//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LooperAnalyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LooperAnalyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked element is not a valid Linq expression..
        /// </summary>
        internal static string InvalidNodeAnalyzerDescription {
            get {
                return ResourceManager.GetString("InvalidNodeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked element is not a valid Linq expression..
        /// </summary>
        internal static string InvalidNodeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("InvalidNodeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked element is not a valid Linq expression..
        /// </summary>
        internal static string InvalidNodeAnalyzerTitle {
            get {
                return ResourceManager.GetString("InvalidNodeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression can be optimized to a loop if refactored first..
        /// </summary>
        internal static string NeedsRefactoringAnalyzerDescription {
            get {
                return ResourceManager.GetString("NeedsRefactoringAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression &apos;{0}&apos; can be optimized to a loop if refactored first..
        /// </summary>
        internal static string NeedsRefactoringAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NeedsRefactoringAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential optimization..
        /// </summary>
        internal static string NeedsRefactoringAnalyzerTitle {
            get {
                return ResourceManager.GetString("NeedsRefactoringAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression is marked for optimization but cannot be optimized. This will have no affect on code generation. Linq expressions should end at consumer methods like &apos;ToArray&apos;, &apos;ToList&apos;, &apos;FirstOrDefault&apos;, etc..
        /// </summary>
        internal static string NoConsumerAnalyzerDescription {
            get {
                return ResourceManager.GetString("NoConsumerAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression is marked but no suitable consumer found..
        /// </summary>
        internal static string NoConsumerAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NoConsumerAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression is marked but no suitable consumer found..
        /// </summary>
        internal static string NoConsumerAnalyzerTitle {
            get {
                return ResourceManager.GetString("NoConsumerAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression can be optimized to a loop..
        /// </summary>
        internal static string OptimizableNodeAnalyzerDescription {
            get {
                return ResourceManager.GetString("OptimizableNodeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression &apos;{0}&apos; can be optimized to a loop..
        /// </summary>
        internal static string OptimizableNodeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("OptimizableNodeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linq expression can be optimized to a loop..
        /// </summary>
        internal static string OptimizableNodeAnalyzerTitle {
            get {
                return ResourceManager.GetString("OptimizableNodeAnalyzerTitle", resourceCulture);
            }
        }
    }
}
